services:
    api:
        build: .
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app:ro  #sync local files w/ container file in read only
        # command:
        #     - uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload

    postgres:
        image: postgres
        env_file:
            - ./.env
        volumes:
            - postgres_db:/var/lib/postgresql/data
volumes:
    postgres_db: